name: Build ARM64 Debian 12 deb

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GO_VERSION: '1.17'
  FLUTTER_VERSION: '2.10.3'
  ANDROID_NDK_VERSION: "23.1.7779620"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      # 检出主仓库代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      # 列出主仓库工作目录内容
      - name: List main working directory
        run: ls -al

      # 检出依赖仓库代码
      - name: Checkout core
        uses: actions/checkout@v3
        with:
          repository: 'niuhuan/pikapika-go-core'
          token: ${{ secrets.GH_TOKEN }}
          path: 'go'

      # 列出依赖仓库工作目录内容
      - name: List go working directory
        run: ls -al go

      # 设置 Go 环境
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # 缓存 Go 模块
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 设置 Flutter 环境
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: x64

      # 安装 ARM64 构建依赖
      - name: Install ARM64 build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y crossbuild-essential-arm64 debhelper

      # 构建项目
      - name: Build project
        run: |
          cd go/mobile
          gomobile init
          gomobile bind -androidapi 21 -target=android/arm64 -o lib/Mobile.aar ./
          cd ../..
          flutter build apk --target-platform android-arm64

      # 创建 Debian 包结构
      - name: Create Debian package structure
        run: |
          mkdir -p deb_package/DEBIAN
          mkdir -p deb_package/usr/bin
          cp build/app/outputs/flutter-apk/app-release.apk deb_package/usr/bin/
          cat << EOF > deb_package/DEBIAN/control
          Package: pikapika
          Version: 1.8.14
          Architecture: arm64
          Maintainer: Your Name <your.email@example.com>
          Description: A visually appealing, easy-to-use, ad-free manga client
          EOF

      # 打包为 .deb 文件
      - name: Build deb package
        run: |
          dpkg-deb --build deb_package pikapika_1.8.14_arm64.deb

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-deb-package
          path: pikapika_1.8.14_arm64.deb
          retention-days: 3
